def checkBox_tela_adicionais_sem(tela):
    telaAdicionais = tela

    telaAdicionais.c1.setChecked(False)
    telaAdicionais.c2.setChecked(False)
    telaAdicionais.c3.setChecked(False)
    telaAdicionais.c4.setChecked(False)
    telaAdicionais.c5.setChecked(False)
    telaAdicionais.c6.setChecked(False)
    telaAdicionais.c7.setChecked(False)
    telaAdicionais.c8.setChecked(False)
    telaAdicionais.c9.setChecked(False)
    telaAdicionais.c10.setChecked(False)
    telaAdicionais.c11.setChecked(False)
    telaAdicionais.c12.setChecked(False)
    telaAdicionais.c13.setChecked(False)
    telaAdicionais.c14.setChecked(False)
    telaAdicionais.c15.setChecked(False)
    telaAdicionais.c16.setChecked(False)
    telaAdicionais.c17.setChecked(False)
    telaAdicionais.c18.setChecked(False)
    telaAdicionais.c19.setChecked(False)
    telaAdicionais.c20.setChecked(False)
    telaAdicionais.c21.setChecked(False)
    telaAdicionais.c22.setChecked(False)
    telaAdicionais.c23.setChecked(False)
    telaAdicionais.c24.setChecked(False)
    telaAdicionais.c25.setChecked(False)
    telaAdicionais.c26.setChecked(False)
    telaAdicionais.c27.setChecked(False)
    telaAdicionais.c28.setChecked(False)
    telaAdicionais.c29.setChecked(False)
    telaAdicionais.c30.setChecked(False)
    telaAdicionais.c31.setChecked(False)
    telaAdicionais.c32.setChecked(False)
    telaAdicionais.c33.setChecked(False)
    telaAdicionais.c34.setChecked(False)
    telaAdicionais.c35.setChecked(False)
    telaAdicionais.c36.setChecked(False)
    telaAdicionais.c37.setChecked(False)
    telaAdicionais.c38.setChecked(False)
    telaAdicionais.c39.setChecked(False)

def checkBox_tela_adicionais_com(tela):
    telaAdicionais = tela

    telaAdicionais.checkBox1.setChecked(False)
    telaAdicionais.checkBox2.setChecked(False)
    telaAdicionais.checkBox3.setChecked(False)
    telaAdicionais.checkBox4.setChecked(False)
    telaAdicionais.checkBox5.setChecked(False)
    telaAdicionais.checkBox6.setChecked(False)
    telaAdicionais.checkBox7.setChecked(False)
    telaAdicionais.checkBox8.setChecked(False)
    telaAdicionais.checkBox9.setChecked(False)
    telaAdicionais.checkBox10.setChecked(False)
    telaAdicionais.checkBox11.setChecked(False)
    telaAdicionais.checkBox12.setChecked(False)
    telaAdicionais.checkBox13.setChecked(False)
    telaAdicionais.checkBox14.setChecked(False)
    telaAdicionais.checkBox15.setChecked(False)
    telaAdicionais.checkBox16.setChecked(False)
    telaAdicionais.checkBox17.setChecked(False)
    telaAdicionais.checkBox18.setChecked(False)
    telaAdicionais.checkBox19.setChecked(False)
    telaAdicionais.checkBox20.setChecked(False)
    telaAdicionais.checkBox21.setChecked(False)
    telaAdicionais.checkBox22.setChecked(False)
    telaAdicionais.checkBox23.setChecked(False)
    telaAdicionais.checkBox24.setChecked(False)
    telaAdicionais.checkBox25.setChecked(False)
    telaAdicionais.checkBox26.setChecked(False)
    telaAdicionais.checkBox27.setChecked(False)
    telaAdicionais.checkBox28.setChecked(False)
    telaAdicionais.checkBox29.setChecked(False)
    telaAdicionais.checkBox30.setChecked(False)
    telaAdicionais.checkBox31.setChecked(False)
    telaAdicionais.checkBox32.setChecked(False)
    telaAdicionais.checkBox33.setChecked(False)
    telaAdicionais.checkBox34.setChecked(False)
    telaAdicionais.checkBox35.setChecked(False)
    telaAdicionais.checkBox36.setChecked(False)
    telaAdicionais.checkBox37.setChecked(False)
    telaAdicionais.checkBox38.setChecked(False)
    telaAdicionais.checkBox39.setChecked(False)
    telaAdicionais.umSabor.setChecked(False)
    telaAdicionais.doisSabores.setChecked(False)
    telaAdicionais.tresSabores.setChecked(False)
    telaAdicionais.quatroSabores.setChecked(False)

def checkBox_tela_pedidos_esfiha(tela):
    telaPrincipal = tela

    telaPrincipal.esfihas_1.setChecked(False)
    telaPrincipal.esfihas_2.setChecked(False)
    telaPrincipal.esfihas_3.setChecked(False)
    telaPrincipal.esfihas_4.setChecked(False)
    telaPrincipal.esfihas_5.setChecked(False)
    telaPrincipal.esfihas_6.setChecked(False)
    telaPrincipal.esfihas_7.setChecked(False)
    telaPrincipal.esfihas_8.setChecked(False)
    telaPrincipal.esfihas_9.setChecked(False)
    telaPrincipal.esfihas_10.setChecked(False)
    telaPrincipal.esfihas_11.setChecked(False)
    telaPrincipal.esfihas_12.setChecked(False)
    telaPrincipal.esfihas_13.setChecked(False)
    telaPrincipal.esfihas_14.setChecked(False)
    telaPrincipal.esfihas_15.setChecked(False)
    telaPrincipal.esfihas_16.setChecked(False)
    telaPrincipal.esfihas_17.setChecked(False)
    telaPrincipal.esfihas_18.setChecked(False)
    telaPrincipal.esfihas_19.setChecked(False)
    telaPrincipal.esfihas_20.setChecked(False)
    telaPrincipal.esfihas_21.setChecked(False)
    telaPrincipal.esfihas_22.setChecked(False)
    telaPrincipal.esfihas_23.setChecked(False)
    telaPrincipal.esfihas_24.setChecked(False)
    telaPrincipal.esfihas_25.setChecked(False)
    telaPrincipal.esfihas_26.setChecked(False)
    telaPrincipal.esfihas_27.setChecked(False)
    telaPrincipal.esfihas_28.setChecked(False)
    telaPrincipal.esfihas_29.setChecked(False)
    telaPrincipal.esfihas_30.setChecked(False)

def checkBox_tela_pedidos_refrigerante(tela):
    telaPrincipal = tela

    telaPrincipal.refri_1.setChecked(False)
    telaPrincipal.refri_2.setChecked(False)
    telaPrincipal.refri_3.setChecked(False)
    telaPrincipal.refri_4.setChecked(False)
    telaPrincipal.refri_5.setChecked(False)
    telaPrincipal.refri_6.setChecked(False)
    telaPrincipal.refri_7.setChecked(False)
    telaPrincipal.refri_8.setChecked(False)
    telaPrincipal.refri_9.setChecked(False)
    telaPrincipal.refri_10.setChecked(False)
    telaPrincipal.refri_11.setChecked(False)
    telaPrincipal.refri_12.setChecked(False)
    telaPrincipal.refri_13.setChecked(False)
    telaPrincipal.refri_14.setChecked(False)
    telaPrincipal.refri_15.setChecked(False)
    telaPrincipal.refri_16.setChecked(False)
    telaPrincipal.refri_17.setChecked(False)
    telaPrincipal.refri_18.setChecked(False)
    telaPrincipal.refri_19.setChecked(False)
    telaPrincipal.refri_20.setChecked(False)
    telaPrincipal.refri_21.setChecked(False)
    telaPrincipal.refri_22.setChecked(False)
    telaPrincipal.refri_23.setChecked(False)
    telaPrincipal.refri_24.setChecked(False)
    telaPrincipal.refri_25.setChecked(False)
    telaPrincipal.refri_26.setChecked(False)
    telaPrincipal.refri_27.setChecked(False)
    telaPrincipal.refri_28.setChecked(False)
    telaPrincipal.refri_29.setChecked(False)
    telaPrincipal.refri_30.setChecked(False)

def checkBox_tela_pedidos_outros(tela):
    telaPrincipal = tela

    telaPrincipal.checkBox2_5.setChecked(False)
    telaPrincipal.checkBox2_4.setChecked(False)
    telaPrincipal.checkBox3_4.setChecked(False)
    telaPrincipal.checkBox4_4.setChecked(False)
    telaPrincipal.checkBox22_5.setChecked(False)
    telaPrincipal.checkBox22_4.setChecked(False)
    telaPrincipal.checkBox23_4.setChecked(False)
    telaPrincipal.checkBox24_4.setChecked(False)
    telaPrincipal.checkBox42_9.setChecked(False)
    telaPrincipal.checkBox42_7.setChecked(False)
    telaPrincipal.checkBox43_7.setChecked(False)
    telaPrincipal.checkBox44_7.setChecked(False)

def checkBox_tela_pedidos_pizzas(tela):
    telaPrincipal = tela

    telaPrincipal.checkBox1.setChecked(False)
    telaPrincipal.checkBox2.setChecked(False)
    telaPrincipal.checkBox3.setChecked(False)
    telaPrincipal.checkBox4.setChecked(False)
    telaPrincipal.checkBox5.setChecked(False)
    telaPrincipal.checkBox6.setChecked(False)
    telaPrincipal.checkBox7.setChecked(False)
    telaPrincipal.checkBox8.setChecked(False)
    telaPrincipal.checkBox9.setChecked(False)
    telaPrincipal.checkBox10.setChecked(False)
    telaPrincipal.checkBox11.setChecked(False)
    telaPrincipal.checkBox12.setChecked(False)
    telaPrincipal.checkBox13.setChecked(False)
    telaPrincipal.checkBox14.setChecked(False)
    telaPrincipal.checkBox15.setChecked(False)
    telaPrincipal.checkBox16.setChecked(False)
    telaPrincipal.checkBox17.setChecked(False)
    telaPrincipal.checkBox18.setChecked(False)
    telaPrincipal.checkBox19.setChecked(False)
    telaPrincipal.checkBox20.setChecked(False)
    telaPrincipal.checkBox21.setChecked(False)
    telaPrincipal.checkBox22.setChecked(False)
    telaPrincipal.checkBox23.setChecked(False)
    telaPrincipal.checkBox24.setChecked(False)
    telaPrincipal.checkBox25.setChecked(False)
    telaPrincipal.checkBox26.setChecked(False)
    telaPrincipal.checkBox27.setChecked(False)
    telaPrincipal.checkBox28.setChecked(False)
    telaPrincipal.checkBox29.setChecked(False)
    telaPrincipal.checkBox30.setChecked(False)
    telaPrincipal.checkBox31.setChecked(False)
    telaPrincipal.checkBox32.setChecked(False)
    telaPrincipal.checkBox33.setChecked(False)
    telaPrincipal.checkBox34.setChecked(False)
    telaPrincipal.checkBox35.setChecked(False)
    telaPrincipal.checkBox36.setChecked(False)
    telaPrincipal.checkBox37.setChecked(False)
    telaPrincipal.checkBox38.setChecked(False)
    telaPrincipal.checkBox39.setChecked(False)
    telaPrincipal.checkBox40.setChecked(False)
    telaPrincipal.checkBox41.setChecked(False)
    telaPrincipal.checkBox42.setChecked(False)
    telaPrincipal.checkBox43.setChecked(False)
    telaPrincipal.checkBox44.setChecked(False)
    telaPrincipal.checkBox45.setChecked(False)
    telaPrincipal.checkBox46.setChecked(False)
    telaPrincipal.checkBox47.setChecked(False)
    telaPrincipal.checkBox48.setChecked(False)
    telaPrincipal.checkBox49.setChecked(False)
    telaPrincipal.checkBox50.setChecked(False)
    telaPrincipal.checkBox51.setChecked(False)

def checkBox_atualizacao_bebidas_outros(tela):
    telaAtualizarBebidas = tela

    telaAtualizarBebidas.lata_atualizar.setChecked(False)
    telaAtualizarBebidas.s600_atualizar.setChecked(False)
    telaAtualizarBebidas.umLitro_atualizar.setChecked(False)
    telaAtualizarBebidas.umLmeio_atualizar.setChecked(False)
    telaAtualizarBebidas.doisLitros_atualizar.setChecked(False)
    telaAtualizarBebidas.doisLmeio_atualizar.setChecked(False)
    telaAtualizarBebidas.outros_atualizar.setChecked(False)

def checkBox_atualizacao_adicionais(tela):
    telaAtualizarProdutos = tela

    telaAtualizarProdutos.buttonBroto_atualizar.setChecked(False)
    telaAtualizarProdutos.ButtonSeis_atualizar.setChecked(False)
    telaAtualizarProdutos.ButtonOito_atualizar.setChecked(False)
    telaAtualizarProdutos.ButtonDez_atualizar.setChecked(False)
    telaAtualizarProdutos.sem_adc_atualizar_2.setChecked(False)

def checkBox_atualizacao_pizzas_esfihas(tela):
    telaAtualizarProdutos = tela

    telaAtualizarProdutos.broto_atualizar.setChecked(False)
    telaAtualizarProdutos.seis_atualizar.setChecked(False)
    telaAtualizarProdutos.oito_atualizar.setChecked(False)
    telaAtualizarProdutos.dez_atualizar.setChecked(False)
    telaAtualizarProdutos.esfiha_atualizar.setChecked(False)

def checkBox_excluir_bebidas(tela):
    telaExcluirBebidas = tela

    telaExcluirBebidas.lata.setChecked(False)
    telaExcluirBebidas.s600.setChecked(False)
    telaExcluirBebidas.umLitro.setChecked(False)
    telaExcluirBebidas.umLmeio.setChecked(False)
    telaExcluirBebidas.doisLitros.setChecked(False)
    telaExcluirBebidas.doisLmeio.setChecked(False)

def checkBox_tela_pedido_hide(tela):
    telaPrincipal = tela

    #------- pizzas
    telaPrincipal.checkBox1.hide()
    telaPrincipal.checkBox2.hide()
    telaPrincipal.checkBox3.hide()
    telaPrincipal.checkBox4.hide()
    telaPrincipal.checkBox5.hide()
    telaPrincipal.checkBox6.hide()
    telaPrincipal.checkBox7.hide()
    telaPrincipal.checkBox8.hide()
    telaPrincipal.checkBox9.hide()
    telaPrincipal.checkBox10.hide()
    telaPrincipal.checkBox11.hide()
    telaPrincipal.checkBox12.hide()
    telaPrincipal.checkBox13.hide()
    telaPrincipal.checkBox14.hide()
    telaPrincipal.checkBox15.hide()
    telaPrincipal.checkBox16.hide()
    telaPrincipal.checkBox17.hide()
    telaPrincipal.checkBox18.hide()
    telaPrincipal.checkBox19.hide()
    telaPrincipal.checkBox20.hide()
    telaPrincipal.checkBox21.hide()
    telaPrincipal.checkBox22.hide()
    telaPrincipal.checkBox23.hide()
    telaPrincipal.checkBox24.hide()
    telaPrincipal.checkBox25.hide()
    telaPrincipal.checkBox26.hide()
    telaPrincipal.checkBox27.hide()
    telaPrincipal.checkBox28.hide()
    telaPrincipal.checkBox29.hide()
    telaPrincipal.checkBox30.hide()
    telaPrincipal.checkBox31.hide()
    telaPrincipal.checkBox32.hide()
    telaPrincipal.checkBox33.hide()
    telaPrincipal.checkBox34.hide()
    telaPrincipal.checkBox35.hide()
    telaPrincipal.checkBox36.hide()
    telaPrincipal.checkBox37.hide()
    telaPrincipal.checkBox38.hide()
    telaPrincipal.checkBox39.hide()
    telaPrincipal.checkBox40.hide()
    telaPrincipal.checkBox41.hide()
    telaPrincipal.checkBox42.hide()
    telaPrincipal.checkBox43.hide()
    telaPrincipal.checkBox44.hide()
    telaPrincipal.checkBox45.hide()
    telaPrincipal.checkBox46.hide()
    telaPrincipal.checkBox47.hide()
    telaPrincipal.checkBox48.hide()
    telaPrincipal.checkBox49.hide()
    telaPrincipal.checkBox50.hide()
    telaPrincipal.checkBox51.hide()

    # ------- outros
    telaPrincipal.checkBox2_5.hide()
    telaPrincipal.checkBox2_4.hide()
    telaPrincipal.checkBox3_4.hide()
    telaPrincipal.checkBox4_4.hide()
    telaPrincipal.checkBox22_5.hide()
    telaPrincipal.checkBox22_4.hide()
    telaPrincipal.checkBox23_4.hide()
    telaPrincipal.checkBox24_4.hide()
    telaPrincipal.checkBox42_9.hide()
    telaPrincipal.checkBox42_7.hide()
    telaPrincipal.checkBox43_7.hide()
    telaPrincipal.checkBox44_7.hide()

    # ------- bebidas
    telaPrincipal.refri_1.hide()
    telaPrincipal.refri_2.hide()
    telaPrincipal.refri_3.hide()
    telaPrincipal.refri_4.hide()
    telaPrincipal.refri_5.hide()
    telaPrincipal.refri_6.hide()
    telaPrincipal.refri_7.hide()
    telaPrincipal.refri_8.hide()
    telaPrincipal.refri_9.hide()
    telaPrincipal.refri_10.hide()
    telaPrincipal.refri_11.hide()
    telaPrincipal.refri_12.hide()
    telaPrincipal.refri_13.hide()
    telaPrincipal.refri_14.hide()
    telaPrincipal.refri_15.hide()
    telaPrincipal.refri_16.hide()
    telaPrincipal.refri_17.hide()
    telaPrincipal.refri_18.hide()
    telaPrincipal.refri_19.hide()
    telaPrincipal.refri_20.hide()
    telaPrincipal.refri_21.hide()
    telaPrincipal.refri_22.hide()
    telaPrincipal.refri_23.hide()
    telaPrincipal.refri_24.hide()
    telaPrincipal.refri_25.hide()
    telaPrincipal.refri_26.hide()
    telaPrincipal.refri_27.hide()
    telaPrincipal.refri_28.hide()
    telaPrincipal.refri_29.hide()
    telaPrincipal.refri_30.hide()

    #------- esfihas
    telaPrincipal.esfihas_1.hide()
    telaPrincipal.esfihas_2.hide()
    telaPrincipal.esfihas_3.hide()
    telaPrincipal.esfihas_4.hide()
    telaPrincipal.esfihas_5.hide()
    telaPrincipal.esfihas_6.hide()
    telaPrincipal.esfihas_7.hide()
    telaPrincipal.esfihas_8.hide()
    telaPrincipal.esfihas_9.hide()
    telaPrincipal.esfihas_10.hide()
    telaPrincipal.esfihas_11.hide()
    telaPrincipal.esfihas_12.hide()
    telaPrincipal.esfihas_13.hide()
    telaPrincipal.esfihas_14.hide()
    telaPrincipal.esfihas_15.hide()
    telaPrincipal.esfihas_16.hide()
    telaPrincipal.esfihas_17.hide()
    telaPrincipal.esfihas_18.hide()
    telaPrincipal.esfihas_19.hide()
    telaPrincipal.esfihas_20.hide()
    telaPrincipal.esfihas_21.hide()
    telaPrincipal.esfihas_22.hide()
    telaPrincipal.esfihas_23.hide()
    telaPrincipal.esfihas_24.hide()
    telaPrincipal.esfihas_25.hide()
    telaPrincipal.esfihas_26.hide()
    telaPrincipal.esfihas_27.hide()
    telaPrincipal.esfihas_28.hide()
    telaPrincipal.esfihas_29.hide()
    telaPrincipal.esfihas_30.hide()

def checkBox_tela_adicionais_hide(tela):
    telaAdicionais = tela

    telaAdicionais.checkBox1.hide()
    telaAdicionais.checkBox2.hide()
    telaAdicionais.checkBox3.hide()
    telaAdicionais.checkBox4.hide()
    telaAdicionais.checkBox5.hide()
    telaAdicionais.checkBox6.hide()
    telaAdicionais.checkBox7.hide()
    telaAdicionais.checkBox8.hide()
    telaAdicionais.checkBox9.hide()
    telaAdicionais.checkBox10.hide()
    telaAdicionais.checkBox11.hide()
    telaAdicionais.checkBox12.hide()
    telaAdicionais.checkBox13.hide()
    telaAdicionais.checkBox14.hide()
    telaAdicionais.checkBox15.hide()
    telaAdicionais.checkBox16.hide()
    telaAdicionais.checkBox17.hide()
    telaAdicionais.checkBox18.hide()
    telaAdicionais.checkBox19.hide()
    telaAdicionais.checkBox20.hide()
    telaAdicionais.checkBox21.hide()
    telaAdicionais.checkBox22.hide()
    telaAdicionais.checkBox23.hide()
    telaAdicionais.checkBox24.hide()
    telaAdicionais.checkBox25.hide()
    telaAdicionais.checkBox26.hide()
    telaAdicionais.checkBox27.hide()
    telaAdicionais.checkBox28.hide()
    telaAdicionais.checkBox29.hide()
    telaAdicionais.checkBox30.hide()
    telaAdicionais.checkBox31.hide()
    telaAdicionais.checkBox32.hide()
    telaAdicionais.checkBox33.hide()
    telaAdicionais.checkBox34.hide()
    telaAdicionais.checkBox35.hide()
    telaAdicionais.checkBox36.hide()
    telaAdicionais.checkBox37.hide()
    telaAdicionais.checkBox38.hide()
    telaAdicionais.checkBox39.hide()

    telaAdicionais.c1.hide()
    telaAdicionais.c2.hide()
    telaAdicionais.c3.hide()
    telaAdicionais.c4.hide()
    telaAdicionais.c5.hide()
    telaAdicionais.c6.hide()
    telaAdicionais.c7.hide()
    telaAdicionais.c8.hide()
    telaAdicionais.c9.hide()
    telaAdicionais.c10.hide()
    telaAdicionais.c11.hide()
    telaAdicionais.c12.hide()
    telaAdicionais.c13.hide()
    telaAdicionais.c14.hide()
    telaAdicionais.c15.hide()
    telaAdicionais.c16.hide()
    telaAdicionais.c17.hide()
    telaAdicionais.c18.hide()
    telaAdicionais.c19.hide()
    telaAdicionais.c20.hide()
    telaAdicionais.c21.hide()
    telaAdicionais.c22.hide()
    telaAdicionais.c23.hide()
    telaAdicionais.c24.hide()
    telaAdicionais.c25.hide()
    telaAdicionais.c26.hide()
    telaAdicionais.c27.hide()
    telaAdicionais.c28.hide()
    telaAdicionais.c29.hide()
    telaAdicionais.c30.hide()
    telaAdicionais.c31.hide()
    telaAdicionais.c32.hide()
    telaAdicionais.c33.hide()
    telaAdicionais.c34.hide()
    telaAdicionais.c35.hide()
    telaAdicionais.c36.hide()
    telaAdicionais.c37.hide()
    telaAdicionais.c38.hide()
    telaAdicionais.c39.hide()
